Reworked `checklist` and `reconfig` library commands.
Minor refactoring;
    Removed dependency on `num_chk` variable.
    Updated all instances of `checklist` and `reconfig` to reflect new syntax.

diff --git a/server/hardening/lib/reconfig b/server/hardening/lib/reconfig
--- a/server/hardening/lib/reconfig
+++ b/server/hardening/lib/reconfig
@@ -1,9 +1,22 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2154
+# Parse arguments
+while getopts 'd:' arg; do
+	case "${arg}" in
+		d) delimiter="${OPTARG}";;
+		*)
+			error "Invalid argument."
+			exit 255
+		;;
+	esac
+done
+delimiter="${delimiter:-' '}"
+shift "$(( OPTIND - 1 ))"
+#
 # The divider used to delimitate the key and value; and the target file.
 # Defined via an environment variable to avoid extreme repetition.
 # Remove any existing keys & then add the new entry
-touch "${target_file}"
-grep -qE "^[^#].*$1${delimiter}.*$" "${target_file}" &&
-	sed -i "s/^[^#]*$1.*$/$1${delimiter}$2/" "${target_file}" ||
-	echo -- "$1${delimiter}$2" >>"${target_file}"
+touch "$3"
+grep -qE "^[^#].*$1${delimiter}.*$" <"$3" &&
+	sed -i "s/^[^#]*$1.*$/$1${delimiter}$2/" <"$3"
+echo -- "$1${delimiter}$2" >>"$3"
